### ISSUE TITLE
Error after upgrading to 2022.11.3

### ISSUE THREAD

**Issue by Voxxie** [robbinjanssen/home-assistant-omnik-inverter#140]
Since upgrading to 2022.11.3 it stopped working. 

Error log shows:

```
ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration omnik_inverter: Unable to import component: cannot import name 'Device' from 'omnikinverter' (/usr/local/lib/python3.10/site-packages/omnikinverter/__init__.py)
```

**Comment by klaasnicolaas** [comment]
Can you add a diagnostics file of the integration to your issue? Then we can better find out where this goes wrong

**Comment by Voxxie** [comment]
How can I download it? 
I cannot find the file. 

When try to add a New integration I also get an error:

![Screenshot_2022-11-18-06-30-12-488_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/1845378/202627896-f3b6fd69-1f29-4c90-ba6e-fef79bfa6a21.jpg)

I already redownloaded the component but the problem presists.

**Comment by klaasnicolaas** [comment]
I doubt if this problem is really with us or if it belongs more to Home Assistant's core repository.

**Comment by Voxxie** [comment]
With the 2022.11.5 release the problem is fixed.
